import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "AI-code-assist-app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-screen flex flex-col bg-slate-950 text-slate-100">
        <div className="flex-1">{children}</div>

        <footer className="border-t border-white/10 bg-slate-950/90 backdrop-blur-xl">
          <div className="mx-auto grid max-w-7xl gap-8 px-4 py-10 sm:px-6 lg:grid-cols-[1.2fr_0.8fr_0.9fr] lg:px-8">
            <div>
              <div className="mb-3 flex items-center gap-3">
                <div className="flex h-10 w-10 items-center justify-center rounded-2xl bg-gradient-to-br from-cyan-400 via-indigo-500 to-violet-500 font-semibold text-slate-950 shadow-lg shadow-cyan-500/20">
                  AI
                </div>
                <div>
                  <p className="text-xs font-semibold uppercase tracking-[0.35em] text-cyan-300">Code Review</p>
                  <p className="text-lg font-semibold text-white">Assistant</p>
                </div>
              </div>
              <p className="max-w-md text-sm leading-6 text-slate-400">
                A polished AI-powered review workflow for code, prompts, and project feedback. Built to help developers move faster with clarity and confidence.
              </p>
            </div>

            <div>
              <p className="mb-3 text-sm font-semibold uppercase tracking-[0.35em] text-cyan-300">Contact</p>
              <div className="space-y-2 text-sm text-slate-300">
                <a href="https://github.com/SaurabhPandey016" target="_blank" rel="noreferrer" className="block transition hover:text-white">
                  GitHub: SaurabhPandey016
                </a>
                <a href="https://www.linkedin.com/in/saurabhpandey-/" target="_blank" rel="noreferrer" className="block transition hover:text-white">
                  LinkedIn: saurabhpandey
                </a>
                <a href="mailto:developersaurabh04@gmail.com" className="block transition hover:text-white">
                  Email: developersaurabh04@gmail.com
                </a>
                <a href="tel:+918720026790" className="block transition hover:text-white">
                  Contact: +918720026790
                </a>
              </div>
            </div>

            <div>
              <p className="mb-3 text-sm font-semibold uppercase tracking-[0.35em] text-cyan-300">Developed by</p>
              <div className="rounded-3xl border border-white/10 bg-white/5 p-4">
                <p className="text-lg font-semibold text-white">made with ❤️ by Saurabh pandey</p>
                <p className="mt-2 text-sm text-slate-400">
                  Built with a premium, modern interface for smooth review flow, responsive screens, and cleaner project collaboration.
                </p>
              </div>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
